import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('HOST_IP', username='dadu', password='PASSWORD', key_filename='/home/pi/.ssh/id_rsa')
ftp = ssh.open_sftp()
file=ftp.file('/home/dadu/partha.txt', "w", -1)
file.write('Hello World!')
file.flush()
ftp.close()
ssh.close()
