#!/usr/bin/python
import serial
import time
import mysql.connector
from time import gmtime, strftime
from datetime import datetime
ser = serial.Serial('/dev/ttyACM0', baudrate = 9600)
time.sleep(1)
start = time.time()

count_server_restart=0
while(1):
 conn=mysql.connector.connect(user='root',password='gowsalya',host='10.21.160.201',database='scada')
 mycursor=conn.cursor()
 mycursor.execute("select * FROM DI where id=3") 
 list=mycursor.fetchall()
 lake_well_lora_status=(list[0][2])
 mycursor.execute("select * FROM DI where id=4") 
 list=mycursor.fetchall()
 childrenpark_lora_status=(list[0][2])
 mycursor.execute("select * FROM DI where id=5") 
 list=mycursor.fetchall()
 stuff_club_lora_status=(list[0][2])
 mycursor.execute("select * FROM GSMAI") 
 list=mycursor.fetchall()
 count_rcvd_from_A=(list[0][2]
 mycursor.execute("select * FROM GSMAI where id=6") 
 list=mycursor.fetchall()
 count_rcvd_from_B=(list[0][2]
 mycursor.execute("select * FROM GSMAI where id=7") 
 list=mycursor.fetchall()
 count_rcvd_non_sense=(list[0][2]
 mycursor.execute("select * FROM GSMAI where id=10") 
 list=mycursor.fetchall()
 count_sent_by_server=(list[0][2]
 mycursor.execute("select * FROM GSMAI where id=13") 
 list=mycursor.fetchall()
 count_server_restart=(list[0][2]
 
 

 #print"lakewell, children, and stuff_club comm availabilities respectively are=%s, %s and %s"%(lake_well_lora_status,childrenpark_lora_status,stuff_club_lora_status)
 conn.close()
 mycursor.close()
 end = time.time()
 if(end - start>300 and lake_well_lora_status=='0'):
  print datetime.now()
  time.sleep(.1)
  ser.write(b'a')
  start=end;

 #if(lake_well_lora_status=='0'):
  #ser.write(b'a')
  #print ("lake well lora fail, command given to lake well")
 conn=mysql.connector.connect(user='root',password='gowsalya',host='10.21.160.201',database='scada')
 mycursor=conn.cursor()
 if(ser.inWaiting()>0):
  data=ser.readline().decode().split('\r\n')
  #data=ser.readline();
  print(data[0])
  #print(data)
  #if('deviceA' in data[0] and 'p' in data[0] and 'q' in data[0] and '<' in data[0] and '>' in data[0]):   
   #mycursor.execute("UPDATE GSMAI SET value='%s'WHERE id='%s'" % (data[0][data[0].find('<')+1:data[0].find('>')], 1))
   #print"lakewell data=%s"%(data[0][data[0].find('<')+1:data[0].find('>')])
  #if('deviceB' in data[0] and 'p' in data[0] and 'q' in data[0] and '<' in data[0] and '>' in data[0]):
   #mycursor.execute("UPDATE GSMAI SET value='%s'WHERE id='%s'" % (data[0][data[0].find('<')+1:data[0].find('>')], 2))
   #print"lakewell data=%s"%(data[0][data[0].find('<')+1:data[0].find('>')])

  #if('deviceA' in data[0] and 'p' in data[0] and 'q' in data[0] and '<' in data[0] and '>' in data[0]):   
   #mycursor.execute("insert into gsm_test (id, name, value) values (%d, '%s', '%s')" % (1, datetime.now(),data[0]))
   
  #if('Non-sense' in data[0]):   
   #mycursor.execute("insert into gsm_test (id, name,value) values (%d, '%s', '%s')" % (1, datetime.now(),data[0]))
   
  #if('modem' in data[0]):   
   #mycursor.execute("insert into gsm_test (id, name,value) values (%d, '%s', '%s')" % (1, datetime.now(),data[0])) 

  if('Serial' not in data[0]):   
   mycursor.execute("insert into gsm_test (id, name,value) values (%d, '%s', '%s')" % (1, datetime.now(),data[0]))  
  
   if('deviceA' in data[0] and 'p' in data[0] and 'q' in data[0] and '<' in data[0] and '>' in data[0]): 
    count_rcvd_from_A=count_rcvd_from_A+1
    mycursor.execute("UPDATE GSMAI SET value='%s'WHERE id='%s'" % (count_rcvd_from_A, 5))  
    #mycursor.execute("insert into gsm_test (id, name, value) values (%d, '%s', '%s')" % (1, datetime.now(),"Nos of valid message found from deviceA=%d"%(valid_countA)))

   if('deviceB' in data[0] and 'p' in data[0] and 'q' in data[0] and '<' in data[0] and '>' in data[0]): 
    count_rcvd_from_B=count_rcvd_from_B+1
    mycursor.execute("UPDATE GSMAI SET value='%s'WHERE id='%s'" % (count_rcvd_from_B, 6))  
    #mycursor.execute("insert into gsm_test (id, name, value) values (%d, '%s', '%s')" % (1, datetime.now(),"Nos of valid message found from deviceB=%d"%(valid_countB)))

   if('Non-sense' in data[0]):   
    count_rcvd_non_sense=count_rcvd_non_sense+1 
    mycursor.execute("UPDATE GSMAI SET value='%s'WHERE id='%s'" % (count_rcvd_non_sense, 7))   
    #mycursor.execute("insert into gsm_test (id, name, value) values (%d, '%s', '%s')" % (1, datetime.now(),"Total Nos of non-sense found=%d"%(valid_count_non_sense)))
   
   if('Nos of SMS Sent to' in data[0]):   
    count_sent_by_server=count_sent_by_server+1 
    mycursor.execute("UPDATE GSMAI SET value='%s'WHERE id='%s'" % (count_sent_by_server, 10))  

   if('Starting' in data[0]): 
    count_server_restart=count_server_restart+1
    mycursor.execute("UPDATE GSMAI SET value='%s'WHERE id='%s'" % (count_server_restart, 13))
   
   

   #mycursor.execute("UPDATE GSMAI SET value='%s'WHERE id='%s'" % (data[0][data[0].find('<')+1:data[0].find('>')], 1))
   #print"lakewell data=%s"%(data[0][data[0].find('<')+1:data[0].find('>')])
  #if('deviceB' in data[0] and 'p' in data[0] and 'q' in data[0] and '<' in data[0] and '>' in data[0]):
   #mycursor.execute("UPDATE GSMAI SET value='%s'WHERE id='%s'" % (data[0][data[0].find('<')+1:data[0].find('>')], 2))
   #print"lakewell data=%s"%(data[0][data[0].find('<')+1:data[0].find('>')])

 conn.commit()
 conn.close()
 mycursor.close() 
 #time.sleep(300)

 #if(childrenpark_lora_status=='0'):
  #ser.write(b'b')
  #print ("children park lora fail, command given to children park")
  #do()
#time.sleep(60)
